# Generated by Django 2.1 on 2018-08-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_auto_20180819_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpersonfindernote',
            name='was_truncated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gpersonfinderrecord',
            name='was_truncated',
            field=models.BooleanField(default=False),
        ),
    ]
